### ISSUE TITLE
Requires Google+ API

### ISSUE THREAD

**Issue by robertlevy** [googlesamples/google-photos#11] opened 2018-12-17 02:40 UTC
When I ran the sample I got this error:

```
GooglePlusAPIError: Access Not Configured. Google+ API has not been used in project XXXX before or it is disabled. 
Enable it by visiting https://console.developers.google.com/apis/api/plus.googleapis.com/overview?project=XXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
    at /XXX/REST/PhotoFrame/node_modules/passport-google-oauth20/lib/strategy.js:95:21
   ...
```

This should be mentioned in the readme setup instructions, or perhaps given the dependency should be removed.

**Comment by Armour** [comment] 2019-01-09 00:03
#1

**Comment by jfschmakeit** [comment] 2019-03-06 23:37
Yes, this a dupe of #1 that has been fixed. Closing this one.

**Closed by jfschmakeit** 2019-03-06 23:37 UTC
